# -*- coding: utf-8 -*-
"""gitsearch.v5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xCLBxdSi7HX2YKsLcDjcIQnkYrFVon6t
"""

!pip install pdfplumber groq

from google.colab import userdata
from groq import Groq
import pdfplumber
import time

api_key = userdata.get('GROQ_API_KEY')
client = Groq(api_key=api_key)

from google.colab import files

print("Upload your gitingest txt file")
uploaded = files.upload()
gitingest_file = list(uploaded.keys())[0]

#print("Upload paper 1")
#uploaded = files.upload()
#pdf1 = list(uploaded.keys())[0]

#print("Upload paper 2")
#uploaded = files.upload()
#pdf2 = list(uploaded.keys())[0]

# Load the full knowledge base as one string
with open(gitingest_file, "r", encoding="utf-8") as f:
    full_knowledge_base = f.read()

print(f"Knowledge base size: {len(full_knowledge_base)} characters")

def call_llm(prompt):
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content

def ask_llm(question):
    prompt = f"""You are a strict retrieval-based assistant for a pediatric bone age assessment system.

You have been given the COMPLETE source code and documentation of the digiBONE repository below.

STRICT RULES — follow without exception:
1. Every factual claim MUST end with a citation in the format [filename:line_number]
2. ONLY use information explicitly stated in the knowledge base below
3. NEVER use your own knowledge or outside information
4. If a claim cannot be directly supported by the knowledge base, do NOT make that claim
5. If the knowledge base does not contain enough information to answer, respond with exactly:
   "The knowledge base does not contain sufficient information to answer this question."
6. Do NOT infer, extrapolate, or reason beyond what is explicitly stated

Knowledge Base:
{full_knowledge_base}

Question: {question}

Remember: If you cannot cite it from the knowledge base above, do not say it.
"""
    return call_llm(prompt)

def run_query(question):
    start = time.time()

    answer = ask_llm(question)

    end = time.time()
    print(f"\nAnswer:\n{answer}")
    print(f"\nTime taken: {(end-start)/60:.2f} mins")

run_query("What is MAD?")

run_query("Why is the bone-age assessment for boys and girls different?")

run_query("Is the bone-age assessment associated with diabetes")

run_query("what is the basketball match score")

run_query("can this system be used to estimate the bone age of humans below the age of 17 years")

run_query("How were the segmental GP labels assigned to each image?")

run_query("How are short bone masks preprocessed to generate short-bone segments?")

run_query("What MAD values did the transfer-learned full-hand model achieve on the HCJBA dataset?")