# -*- coding: utf-8 -*-
"""gitSearch.v.3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KLyHTHPIi7SGqi-DIXxTGm75VFBcnqx9

**gitSearch_with_Domain_Restriction_without_pre_defining_scope**
"""

!pip install pdfplumber groq

from google.colab import userdata
from groq import Groq
import pdfplumber
import time

api_key = userdata.get('GROQ_API_KEY')
client = Groq(api_key=api_key)

from google.colab import files

print("Upload your gitingest txt file")
uploaded = files.upload()
gitingest_file = list(uploaded.keys())[0]

#print("Upload paper 1")
#uploaded = files.upload()
#pdf1 = list(uploaded.keys())[0]

#print("Upload paper 2")
#uploaded = files.upload()
#pdf2 = list(uploaded.keys())[0]

def load_pdf(pdf_path):
    lines = []
    with pdfplumber.open(pdf_path) as pdf:
        for i, page in enumerate(pdf.pages):
            text = page.extract_text()
            if text:
                lines.append(f"================================================\n")
                lines.append(f"FILE: {pdf_path} (page {i+1})\n")
                lines.append(f"================================================\n")
                for line in text.splitlines(keepends=True):
                    lines.append(line)
    return lines

with open(gitingest_file, "r", encoding="utf-8") as f:
    lines = f.readlines()

#lines += load_pdf(pdf1)
#lines += load_pdf(pdf2)

print(f"Total lines loaded: {len(lines)}")

def search(query, lines):
    results = []
    for i, line in enumerate(lines):
        if query.lower().replace(" ", "").replace("-", "") in line.lower().replace(" ", "").replace("-", ""):
            current_file = "unknown"
            for j in range(i, 0, -1):
                if lines[j].startswith("FILE:"):
                    current_file = lines[j].replace("FILE:", "").strip()
                    break
            start = max(0, i - 2)
            end = min(len(lines), i + 20)
            snippet = "".join(lines[start:end])
            results.append({
                "file": current_file,
                "line_number": i + 1,
                "snippet": snippet
            })
    return results


def call_llm(prompt):
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content


def extract_words(question):
    prompt = f"""Extract 3-5 keywords strictly from the question below.
Only use words that actually appear in the question.
Do NOT add related terms or your own knowledge.
Return ONLY a comma separated list, nothing else.

Question: {question}
"""
    return call_llm(prompt).split(",")


def filter_results(results, question):
    question_words = set(question.lower().replace("-","").replace(" ","").split())
    scored = []
    for r in results:
        snippet_words = set(r["snippet"].lower().replace("-","").replace(" ","").split())
        score = len(question_words & snippet_words)
        scored.append((score, r))
    scored.sort(key=lambda x: x[0], reverse=True)
    return [r for score, r in scored[:8]]

def ask_llm(question, search_results):
    context = ""
    for r in search_results:
        context += f"\nSource [{r['file']}:{r['line_number']}]\n{r['snippet']}\n---"

    prompt = f"""You are a strict retrieval-based assistant for a pediatric bone age assessment system.

STRICT RULES — follow without exception:
1. Every single sentence MUST end with a citation in the format [filename:line_number]
2. ONLY use information explicitly stated in the context below
3. NEVER use your own knowledge or outside information
4. If a claim cannot be directly supported by a source in the context, do NOT make that claim
5. If the context does not contain enough information to answer, respond with exactly:
   "The knowledge base does not contain sufficient information to answer this question."
6. Do NOT infer, extrapolate, or reason beyond what is explicitly stated in the sources

Context:
{context}

Question: {question}

Remember: If you cannot cite it from the context above, do not say it.
"""
    return call_llm(prompt)


def run_query(question):
    start = time.time()

    keywords = extract_words(question)
    print("Keywords:", keywords)

    results = []
    for keyword in keywords:
        results += search(keyword, lines)

    # deduplicate
    seen = set()
    unique_results = []
    for r in results:
        key = (r["file"], r["line_number"])
        if key not in seen:
            seen.add(key)
            unique_results.append(r)

    print("Unique results:", len(unique_results))

    # scope is determined by the knowledge base
    if len(unique_results) == 0:
        print("Out of scope: No relevant information found in the knowledge base.")
        return

    filtered = filter_results(unique_results, question)
    answer = ask_llm(question, filtered)

    end = time.time()
    print(f"\nAnswer:\n{answer}")
    print(f"\nTime taken: {(end-start)/60:.2f} mins")

run_query("How can one use bone age predictions to predict adult height")

run_query("can this system be used to estimate the bone age of humans below the age of 17 years")

run_query("what is the basketball match score")

run_query("What MAD values did the transfer-learned full-hand model achieve on the HCJBA dataset?")

run_query("What is MAD?")

run_query("I have a hand bone x-ray of my 17 year old kid. can this system be used to predict his bone age?")

run_query("How were the segmental GP labels assigned to each image?")

run_query("How are short bone masks preprocessed to generate short-bone segments?")

run_query("Why is the bone-age assessment for boys and girls different?")

run_query("Is the bone-age assessment for prepubesent boys and girls different?")

run_query("Is the bone-age assessment associated with diabeties")

run_query("Should a child take calcium supplements to improve or match the chronical bone-age associated with their specific age?")