# -*- coding: utf-8 -*-
"""gitSearch.v.4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/137bJHfeGo5NijuYHM_G0OMIjcV8Se1cc

**gitSearch_with_Domain_Restriction_without_pre_defining_scope_using_Sentence_Transformer_with_Semantic_Search**
"""

!pip install sentence-transformers
from sentence_transformers import SentenceTransformer
import numpy as np

!pip install pdfplumber groq

from google.colab import userdata
from groq import Groq
import pdfplumber
import time

api_key = userdata.get('GROQ_API_KEY')
client = Groq(api_key=api_key)

from google.colab import files

print("Upload your gitingest txt file")
uploaded = files.upload()
gitingest_file = list(uploaded.keys())[0]

#print("Upload paper 1")
#uploaded = files.upload()
#pdf1 = list(uploaded.keys())[0]

#print("Upload paper 2")
#uploaded = files.upload()
#pdf2 = list(uploaded.keys())[0]

def load_pdf(pdf_path):
    lines = []
    with pdfplumber.open(pdf_path) as pdf:
        for i, page in enumerate(pdf.pages):
            text = page.extract_text()
            if text:
                lines.append(f"================================================\n")
                lines.append(f"FILE: {pdf_path} (page {i+1})\n")
                lines.append(f"================================================\n")
                for line in text.splitlines(keepends=True):
                    lines.append(line)
    return lines

with open(gitingest_file, "r", encoding="utf-8") as f:
    lines = f.readlines()

#lines += load_pdf(pdf1)
#lines += load_pdf(pdf2)

print(f"Total lines loaded: {len(lines)}")

# Load the sentence transformer model
embedder = SentenceTransformer('all-MiniLM-L6-v2')

chunks = []
CHUNK_SIZE = 15
OVERLAP = 3

# First pass: tag every line with its file
tagged_lines = []
current_file = "unknown"
for line in lines:
    stripped = line.strip()
    if stripped.startswith("FILE:"):
        current_file = stripped.replace("FILE:", "").strip()
        continue
    if stripped.startswith("===") or not stripped:
        continue
    tagged_lines.append({
        "file": current_file,
        "text": stripped
    })

print(f"Tagged lines: {len(tagged_lines)}")

# Second pass: create overlapping chunks
i = 0
while i < len(tagged_lines):
    chunk_slice = tagged_lines[i:i + CHUNK_SIZE]

    # use the most common file in this chunk
    file_names = [t["file"] for t in chunk_slice]
    current_file = max(set(file_names), key=file_names.count)

    chunk_text = " ".join([t["text"] for t in chunk_slice])

    chunks.append({
        "file": current_file,
        "line_number": i + 1,
        "text": chunk_text
    })

    i += CHUNK_SIZE - OVERLAP

print(f"Total chunks: {len(chunks)}")

# Encode
print("Encoding knowledge base...")
chunk_texts = [c["text"] for c in chunks]
chunk_embeddings = embedder.encode(chunk_texts, show_progress_bar=True)
print("Encoding done!")

print("First 5 chunks:")
for c in chunks[:]:
    print(f"File: {c['file']} | Line: {c['line_number']}")
    print(f"Text: {c['text'][:200]}")
    print("---")

print("\nTotal chunks:", len(chunks))

def search(query, lines, top_k=15):
    query_embedding = embedder.encode([query])[0]

    similarities = []
    for i, chunk_embedding in enumerate(chunk_embeddings):
        similarity = np.dot(query_embedding, chunk_embedding) / (
            np.linalg.norm(query_embedding) * np.linalg.norm(chunk_embedding)
        )
        similarities.append((similarity, i))

    similarities.sort(reverse=True)

    results = []
    file_counts = {}

    for similarity_score, idx in similarities:
        chunk = chunks[idx]
        file = chunk["file"]

        # skip unknown chunks
        if file == "unknown":
            continue

        # skip chunks that are mostly HTML or image tags
        text = chunk["text"]
        if text.count("<") > 3 or text.count("img src") > 0:
            continue

        if file_counts.get(file, 0) >= 3:
            continue

        results.append({
            "file": file,
            "line_number": chunk["line_number"],
            "snippet": chunk["text"],
            "score": round(float(similarity_score), 3)
        })

        file_counts[file] = file_counts.get(file, 0) + 1

        if len(results) >= top_k:
            break

    return results

def call_llm(prompt):
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content

def ask_llm(question, search_results):
    context = ""
    for r in search_results:
        context += f"\nSource [{r['file']}:{r['line_number']}]\n{r['snippet']}\n---"

    prompt = f"""You are a strict retrieval-based assistant for a pediatric bone age assessment system.

STRICT RULES — follow without exception:
1. Every single sentence MUST end with a citation in the format [filename:line_number]
2. ONLY use information explicitly stated in the context below
3. NEVER use your own knowledge or outside information
4. If a claim cannot be directly supported by a source in the context, do NOT make that claim
5. If the context does not contain enough information to answer, respond with exactly:
   "The knowledge base does not contain sufficient information to answer this question."
6. Do NOT infer, extrapolate, or reason beyond what is explicitly stated in the sources

Context:
{context}

Question: {question}

Remember: If you cannot cite it from the context above, do not say it.
"""
    return call_llm(prompt)

def run_query(question):
    start = time.time()

    print("Searching knowledge base...")
    results = search(question, lines, top_k=15)

    # print scores to see what's happening
    for r in results:
        print(r["score"], r["file"], r["line_number"])

    # out of scope if best score is very low
    if results[0]["score"] < 0.1:
      print(f"Out of scope: Best match score was only {results[0]['score']}.")
      return

    # only keep results reasonably close to the top score
    top_score = results[0]["score"]
    filtered = [r for r in results if r["score"] >= top_score * 0.6]

    print(f"Relevant chunks found: {len(filtered)}")

    answer = ask_llm(question, filtered)

    end = time.time()
    print(f"\nAnswer:\n{answer}")
    print(f"\nTime taken: {(end-start)/60:.2f} mins")

run_query("What is MAD?")
run_query("What MAD values did the transfer-learned full-hand model achieve on the HCJBA dataset?")
run_query("How are short bone masks preprocessed to generate short-bone segments?")
run_query("How were the segmental GP labels assigned to each image?")
run_query("can this system be used to estimate the bone age of humans below the age of 17 years")
run_query("what is the basketball match score")
run_query("Is the bone-age assessment associated with diabetes")
run_query("Why is the bone-age assessment for boys and girls different?")

run_query("How can one use bone age predictions to predict adult height")

run_query("can this system be used to estimate the bone age of humans below the age of 17 years")

run_query("what is the basketball match score")

run_query("What MAD values did the transfer-learned full-hand model achieve on the HCJBA dataset?")

run_query("What is MAD?")



run_query("I have a hand bone x-ray of my 17 year old kid. can this system be used to predict his bone age?")

run_query("How were the segmental GP labels assigned to each image?")

run_query("How are short bone masks preprocessed to generate short-bone segments?")

run_query("Why is the bone-age assessment for boys and girls different?")

run_query("Is the bone-age assessment for prepubesent boys and girls different?")

run_query("Is the bone-age assessment associated with diabeties")

run_query("Should a child take calcium supplements to improve or match the chronical bone-age associated with their specific age?")